name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualizado a la última versión

    - name: Set up CMake
      uses: lukka/get-cmake@v3.21.2  # Verifica si hay una versión más reciente

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the calculator
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./calculadora  # Asegúrate de que este archivo se genere correctamente

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualizado a la última versión

    - name: Deploy to production
      run: echo "Deploying to production server"

